# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_kite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kitesession',
            index=models.Index(fields=['user', 'is_active'], name='broker_kite_user_id_470ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='kitesession',
            index=models.Index(fields=['kite_user_id'], name='broker_kite_kite_us_fdd9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='kitesession',
            index=models.Index(fields=['is_active', 'session_expires_at'], name='broker_kite_is_acti_cd1ab6_idx'),
        ),
    ]
