# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['level', 'created_at'], name='audit_audit_level_e6924b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_audit_entity__73f5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id', 'created_at'], name='audit_audit_request_4d8918_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx'),
        ),
    ]
