# Generated by Django 5.2.11 on 2026-02-14 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('admin', 'Admin'), ('telegram', 'Telegram')], default='dashboard', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('timeout_policy', models.CharField(choices=[('auto_reject', 'Auto Reject'), ('auto_pause', 'Auto Pause Agent'), ('escalate', 'Escalate To Admin')], default='auto_reject', max_length=16)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('intent_payload', models.JSONField(blank=True, default=dict)),
                ('risk_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='agents.agent')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('admin', 'Admin'), ('telegram', 'Telegram')], max_length=16)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_query_id', models.CharField(max_length=128, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_callback_events', to='approvals.approvalrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'expires_at'], name='approvals_a_status_f7bf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='approvals_a_agent_i_bbcaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='approvals_a_request_48c6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['decided_by', 'decided_at'], name='approvals_a_decided_09e2af_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='approvals_a_channel_86531e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['approval_request', 'created_at'], name='approvals_a_approva_63e748_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['actor', 'created_at'], name='approvals_a_actor_i_63d3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['channel', 'decision', 'created_at'], name='approvals_a_channel_577524_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(condition=models.Q(('actor__isnull', False)), fields=('approval_request', 'actor'), name='unique_decision_per_actor_per_request'),
        ),
        migrations.AddIndex(
            model_name='telegramcallbackevent',
            index=models.Index(fields=['approval_request', 'created_at'], name='approvals_t_approva_835389_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramcallbackevent',
            index=models.Index(fields=['telegram_user_id', 'created_at'], name='approvals_t_telegra_d04232_idx'),
        ),
    ]
