# Generated by Django 5.2.11 on 2026-02-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_query_id', models.CharField(max_length=128, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_callback_events', to='approvals.approvalrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['approval_request', 'created_at'], name='approvals_t_approva_835389_idx')],
            },
        ),
    ]
