# Generated by Django 5.2.11 on 2026-02-14 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_telegramcallbackevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(condition=models.Q(('actor__isnull', False)), fields=('approval_request', 'actor'), name='unique_decision_per_actor_per_request'),
        ),
    ]
