# Generated by Django 5.2.11 on 2026-02-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalrequest_required_approvals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='timeout_policy',
            field=models.CharField(choices=[('auto_reject', 'Auto Reject'), ('auto_pause', 'Auto Pause Agent'), ('escalate', 'Escalate To Admin')], default='auto_reject', max_length=16),
        ),
    ]
