# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_agents_agen_status_65a1e3_idx_and_more'),
        ('approvals', '0004_approvalrequest_escalated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['approval_request', 'created_at'], name='approvals_a_approva_63e748_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['actor', 'created_at'], name='approvals_a_actor_i_63d3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['channel', 'decision', 'created_at'], name='approvals_a_channel_577524_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'expires_at'], name='approvals_a_status_f7bf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['agent', 'status', 'created_at'], name='approvals_a_agent_i_bbcaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='approvals_a_request_48c6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['decided_by', 'decided_at'], name='approvals_a_decided_09e2af_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='approvals_a_channel_86531e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramcallbackevent',
            index=models.Index(fields=['telegram_user_id', 'created_at'], name='approvals_t_telegra_d04232_idx'),
        ),
    ]
