# Generated by Django 5.2.11 on 2026-02-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('max_order_notional', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('max_position_notional', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=2000, max_digits=14)),
                ('max_orders_per_day', models.PositiveIntegerField(default=20)),
                ('allowed_symbols', models.JSONField(blank=True, default=list)),
                ('require_market_hours', models.BooleanField(default=True)),
                ('allow_shorting', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_risk_policy_name_per_owner')],
            },
        ),
    ]
