# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskpolicy',
            index=models.Index(fields=['owner', 'is_default'], name='risk_riskpo_owner_i_20912d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskpolicy',
            index=models.Index(fields=['is_default'], name='risk_riskpo_is_defa_5ad4f8_idx'),
        ),
    ]
