# Generated by Django 5.2.11 on 2026-02-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('execution_mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=16)),
                ('approval_mode', models.CharField(choices=[('none', 'None'), ('always', 'Always'), ('risk_based', 'Risk Based')], default='risk_based', max_length=16)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_predictive', models.BooleanField(default=False)),
                ('is_auto_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('risk_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='risk.riskpolicy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='unique_agent_slug_per_owner')],
            },
        ),
    ]
