# Generated by Django 5.2.11 on 2026-02-14 15:47

import apps.agents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('execution_mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=16)),
                ('approval_mode', models.CharField(choices=[('none', 'None'), ('always', 'Always'), ('risk_based', 'Risk Based')], default='risk_based', max_length=16)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_predictive', models.BooleanField(default=False)),
                ('is_auto_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='agent_approvals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('risk_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='risk.riskpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('query', models.TextField()),
                ('model', models.CharField(blank=True, max_length=128)),
                ('max_steps', models.PositiveSmallIntegerField(default=6)),
                ('steps_executed', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('result_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='agents.agent')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentanalysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('callback_url', models.URLField(max_length=500)),
                ('signing_secret_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_types', models.JSONField(blank=True, default=apps.agents.models.default_analysis_notification_event_types)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('analysis_run.completed', 'Analysis Run Completed'), ('analysis_run.failed', 'Analysis Run Failed'), ('analysis_run.canceled', 'Analysis Run Canceled')], max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='agents.agentanalysisrun')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='agents.agentanalysiswebhookendpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'updated_at'], name='agents_agen_status_65a1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['owner', 'status'], name='agents_agen_owner_i_d16368_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_auto_enabled', 'status'], name='agents_agen_is_auto_22a8b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_agent_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_bd4748_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['status', 'created_at'], name='agents_agen_status_09d07e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['requested_by', 'created_at'], name='agents_agen_request_8bb381_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisevent',
            index=models.Index(fields=['run', 'sequence'], name='agents_agen_run_id_8f1985_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisevent',
            index=models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_16c775_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysisevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_analysis_event_sequence_per_run'),
        ),
        migrations.AddIndex(
            model_name='agentanalysiswebhookendpoint',
            index=models.Index(fields=['owner', 'is_active'], name='agents_agen_owner_i_b20e9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysiswebhookendpoint',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_analysis_webhook_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['run', 'created_at'], name='agents_agen_run_id_7a9e73_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='agents_agen_endpoin_db91a2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_dcdbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['success', 'next_retry_at'], name='agents_agen_success_f112d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysisnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'run', 'event_type'), name='unique_analysis_delivery_per_endpoint_run_event'),
        ),
    ]
