# Generated by Django 5.2.11 on 2026-02-14 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='agent_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
