# Generated by Django 5.2.11 on 2026-02-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_approvers_agent_required_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('query', models.TextField()),
                ('model', models.CharField(blank=True, max_length=128)),
                ('max_steps', models.PositiveSmallIntegerField(default=6)),
                ('steps_executed', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('result_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='agents.agent')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentanalysisrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_bd4748_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['status', 'created_at'], name='agents_agen_status_09d07e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisevent',
            index=models.Index(fields=['run', 'sequence'], name='agents_agen_run_id_8f1985_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisevent',
            index=models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_16c775_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysisevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_analysis_event_sequence_per_run'),
        ),
    ]
