# Generated by Django 5.2.11 on 2026-02-14 12:39

import apps.agents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentanalysisrun_agentanalysisevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAnalysisWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('callback_url', models.URLField(max_length=500)),
                ('signing_secret_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_types', models.JSONField(blank=True, default=apps.agents.models.default_analysis_notification_event_types)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalysisNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('analysis_run.completed', 'Analysis Run Completed'), ('analysis_run.failed', 'Analysis Run Failed'), ('analysis_run.canceled', 'Analysis Run Canceled')], max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='agents.agentanalysisrun')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='agents.agentanalysiswebhookendpoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentanalysiswebhookendpoint',
            index=models.Index(fields=['owner', 'is_active'], name='agents_agen_owner_i_b20e9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysiswebhookendpoint',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_analysis_webhook_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['run', 'created_at'], name='agents_agen_run_id_7a9e73_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='agents_agen_endpoin_db91a2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_dcdbe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentanalysisnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'run', 'event_type'), name='unique_analysis_delivery_per_endpoint_run_event'),
        ),
    ]
