# Generated by Django 5.2.11 on 2026-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentanalysiswebhookendpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanalysisnotificationdelivery',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentanalysisnotificationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentanalysisnotificationdelivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentanalysisnotificationdelivery',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='agentanalysisnotificationdelivery',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agentanalysisnotificationdelivery',
            index=models.Index(fields=['success', 'next_retry_at'], name='agents_agen_success_f112d9_idx'),
        ),
    ]
