# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentanalysisnotificationdelivery_attempt_count_and_more'),
        ('risk', '0002_riskpolicy_risk_riskpo_owner_i_20912d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status', 'updated_at'], name='agents_agen_status_65a1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['owner', 'status'], name='agents_agen_owner_i_d16368_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_auto_enabled', 'status'], name='agents_agen_is_auto_22a8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentanalysisrun',
            index=models.Index(fields=['requested_by', 'created_at'], name='agents_agen_request_8bb381_idx'),
        ),
    ]
