# Generated by Django 5.2.11 on 2026-02-14 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(max_length=64)),
                ('exchange', models.CharField(default='NSE', max_length=16)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=8)),
                ('quantity', models.PositiveIntegerField()),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL', 'Stop Loss'), ('SL-M', 'Stop Loss Market')], default='MARKET', max_length=16)),
                ('product', models.CharField(choices=[('MIS', 'MIS'), ('CNC', 'CNC'), ('NRML', 'NRML')], default='MIS', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notional_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('queued', 'Queued'), ('placed', 'Placed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('broker_order_id', models.CharField(blank=True, max_length=128)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('broker_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_intents', to='agents.agent')),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_intent', to='approvals.approvalrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
