# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_agents_agen_status_65a1e3_idx_and_more'),
        ('approvals', '0005_approvaldecision_approvals_a_approva_63e748_idx_and_more'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['status', 'created_at'], name='execution_t_status_3a852f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['agent', 'created_at'], name='execution_t_agent_i_a83a54_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['symbol', 'created_at'], name='execution_t_symbol_8bd079_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['broker_order_id'], name='execution_t_broker__14d27b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['placed_at'], name='execution_t_placed__049a3d_idx'),
        ),
    ]
