# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['telegram_chat_id'], name='accounts_us_telegra_0acb54_idx'),
        ),
    ]
