# Generated by Django 5.2.11 on 2026-02-14 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.CharField(choices=[('kite', 'Zerodha Kite')], default='kite', max_length=32)),
                ('alias', models.CharField(default='default', max_length=64)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret_encrypted', models.TextField()),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'broker', 'alias'), name='unique_broker_credential_per_user_alias')],
            },
        ),
        migrations.CreateModel(
            name='LlmCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter')], default='openrouter', max_length=32)),
                ('api_key_encrypted', models.TextField()),
                ('default_model', models.CharField(default='openai/gpt-4o-mini', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_llm_credential_per_user_provider')],
            },
        ),
    ]
