# Generated by Django 5.2.11 on 2026-02-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument_token', models.BigIntegerField(unique=True)),
                ('tradingsymbol', models.CharField(max_length=64)),
                ('exchange', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('segment', models.CharField(blank=True, max_length=32)),
                ('instrument_type', models.CharField(blank=True, max_length=32)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tradingsymbol', 'exchange', 'segment'), name='unique_symbol_exchange_segment')],
            },
        ),
        migrations.CreateModel(
            name='TickSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('oi', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='kite_ticker', max_length=32)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='market_data.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['instrument', 'created_at'], name='market_data_instrum_1578dc_idx')],
            },
        ),
    ]
