# Generated by Django 5.2.11 on 2026-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['exchange', 'tradingsymbol'], name='market_data_exchang_1b1149_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['is_active', 'exchange'], name='market_data_is_acti_8667c8_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['name'], name='market_data_name_425101_idx'),
        ),
        migrations.AddIndex(
            model_name='ticksnapshot',
            index=models.Index(fields=['source', 'created_at'], name='market_data_source_ddfcf9_idx'),
        ),
    ]
